### ISSUE TITLE
Question: Any tips on implementing scroll loop?

### ISSUE THREAD

**Issue by CJHersh** [TimRoussilhe/smooth#2]
1) Awesome library - Thank you!
2) I've been struggling to create a looping scroll interaction w/ this lib - Curious if you have any suggestions regarding implementation.

**Comment by TimRoussilhe** [comment]
Hey CJ, thanks for the feedback and trying the library even with the lack of good documentation :). 

If I had to create a loop. I would monitor the bounds of your page inside the run method. For example if the scroll position will reach the bottom of the page, then you would have to reset the position to zero + the potential speed of the scroll to make it smooth).

Something like this : 
`
if(this.vars.current >= this.vars.documentHeight -  this.vars.height){
  const positionSpeedOffset = 0 + this.vars.current -this.vars.old
  this.vars.current = positionSpeedOffset;
  this.forceTransformStyle(positionSpeedOffset);
}
`

And then the same for the other direction if you need a loop both way.

To be fair i'm away of my computer and this solution is purely theoretical but I hope this might help you.
